rideup/urls.py
from django.conf.urls import patterns, url

from rideup import views

urlpatterns = patterns('', 
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.create, name='create'),
    url(r'^showrides/$', views.showrides, name='showrides'),
    url(r'^register_success/$', views.register_success, name='register_success'),
    url(r'^getmaprides/$', views.get_map_rides, name='get_map_rides'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'rideup/index.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'}, name='logout'),
)

rideup_site/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('rideup.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

rideup/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User

class Ride(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    created_date = models.DateTimeField()
    ride_time = models.DateTimeField()
    description = models.CharField(max_length=500)
    lat = models.DecimalField(max_digits=20, decimal_places=15)
    lng = models.DecimalField(max_digits=20, decimal_places=15)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.address

class CreateRideForm(ModelForm):
    class Meta:
        model = Ride

rideup/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from rideup.models import Ride, CreateRideForm
from datetime import datetime
import json

def index(request):
    return render(request, 'rideup/index.html')

@login_required
def create(request):
    if request.method == 'POST':
        form = CreateRideForm(request.POST.copy())
        ride_time = datetime.strptime(form.data['ride_time'], '%B %d %Y @ %I:%M %p')
        form.data['ride_time'] = ride_time
        form.data['created_date'] = datetime.now()
        form.data['user'] = request.user.id
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/showrides/')
        else:
            return HttpResponseRedirect('')
    else:
        form = CreateRideForm()
    return render(request, 'rideup/create.html', {'form' : form})


def showrides(request):
    return render(request, 'rideup/showrides.html')


def get_map_rides(request):
    if request.is_ajax():
        northeastLat = request.GET['northeastLat']
        northeastLng = request.GET['northeastLng']
        southwestLat = request.GET['southwestLat']
        southwestLng = request.GET['southwestLng']

        qry = """
            select * from rideup_ride
            where lat < %s
                and lng < %s
                and lat > %s
                and lng > %s
            """ % (northeastLat, northeastLng, southwestLat, southwestLng)

        ride_ids = []
        ride_list = []
        for ride in Ride.objects.raw(qry):
            ride_list.append(dict(user=User.objects.get(pk=ride.user.id).username,
                                 lat=str(ride.lat), lng=str(ride.lng), name=ride.name,
                                 address=ride.address, description=ride.description,
                                 ride_time=ride.ride_time.strftime("%b %-d, %-I:%M %p"),
                                 ride_id=ride.id))
            ride_ids.append(ride.id)

        response_dict = dict(rideIDs=ride_ids,
                             rideList=ride_list)

        return HttpResponse(json.dumps(response_dict),
                            mimetype='application/json')
    else:
        return HttpResponse()


def register(request):
    form = UserCreationForm(request.POST.copy())
    if form.is_valid():
        form.save()
        new_user = authenticate(username=request.POST['username'],
                                password=request.POST['password1'])
        login(request, new_user)
        return HttpResponseRedirect('/register_success/')
    else:
        return HttpResponseRedirect('/')

@login_required
def register_success(request):
    return render(request, 'rideup/register_success.html')

rideup/templates/rideup/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        {% block head %}{% endblock %}
        <link rel="stylesheet" href="{% static 'rideup/css/bootstrap.min.css' %}" media="screen">
        <link rel="stylesheet" href="{% static 'rideup/css/style.css' %}" type="text/css" />
        <link href="/static/rideup/img/favicon.ico" rel="icon" type="image/x-icon">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
	    <nav class="navbar navbar-default" role="navigation">
	        <div class="container">
	            <div class="navbar-header">
	                <button type="button" class="navbar-toggle" data-toggle="collapse"
	                        data-target="#navbar-rideup-collapse">
	                    <span class="sr-only">Toggle navigation</span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                </button>
	                <a class="navbar-brand" href="#">RideUp</a>
	            </div>
	            <div class="collapse navbar-collapse" id="navbar-rideup-collapse">
	                <ul class="nav navbar-nav">
	                  <li><a id="home-link" href="{% url 'index' %}">Home</a></li>
	                  <li><a id="create-link" href="{% url 'create' %}">Create a Ride!</a></li>
	                  <li><a id="showrides-link" href="{% url 'showrides' %}">Show Rides</a></li>
	                </ul>
	            </div>
            </div>
        </nav>
        {% block content %}{% endblock %}
        <script type="text/javascript" src="{% static 'rideup/js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'rideup/js/bootstrap.min.js' %}"></script>
        {% block foot %}{% endblock %}
    </body>
</html>

rideup/templates/rideup/create.html
{% extends "rideup/base.html" %}
{% load staticfiles %}

{% block head %}
<title>RideUp - Create a ride</title>
<link rel="stylesheet" href="{% static 'rideup/css/jquery-ui-1.10.3.custom.min.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'rideup/css/jquery-ui-timepicker-addon.min.css' %}" type="text/css" />
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Create a ride!</h2>
            <form action="{% url 'create' %}" method="post" id="create-form">
            {% csrf_token %}
                <div class="form-group">
                    <label class="control-label">Address:</label>
                    <input type="text" id="id_address" name="address"
                           placeholder="Search for an address"
                           class="form-control">
                    <input type="hidden" id="id_lat" name="lat">
                    <input type="hidden" id="id_lng" name="lng">
                </div>
                <div class="form-group">
                    <label>Place name:</label>
                    <input type="text" id="id_name" name="name"
                           placeholder="Name of the place you want to meet"
                           class="form-control">
                </div>
                <div class="form-group">
                    <label class="control-label">Ride date/time:</label>
                    <input type="text" id="id_ride_time" name="ride_time"
                           class="form-control" required>
                </div>
                <div class="form-group">
                    <label class="control-label">Description:</label>
                    <textarea id="id_description" name="description"
                              class="form-control"
                              placeholder="Enter a description (route, destination, speed, etc...)"
                              rows="3" required></textarea>
                </div>
                <button type="submit" class="btn">Submit your ride!</button>
            </form>
        </div>
        <div class="col-md-8">
            <div id="map">
                <div id="map_canvas"></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block foot %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAHu3tscS1tG243nstn6jiAS9L2kD1OwtQ&libraries=places&sensor=false"></script>
<script type="text/javascript" src="{% static 'rideup/js/rideup-create.js' %}"></script>
<script type="text/javascript" src="{% static 'rideup/js/jquery-ui-1.10.3.custom.min.js' %}"></script>
<script type="text/javascript" src="{% static 'rideup/js/jquery-ui-timepicker-addon.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $("#create-link").parent().addClass('active');
        $("#id_ride_time").datetimepicker({
            minDateTime: new Date(),
            dateFormat: "MM d yy",
            timeFormat: "@ h:mm TT"
        });
        $("#id_ride_time").on("keypress", function () {
            return false;
        });
        $("#id_address").on("keypress", function(key) {
            if (key.which == 10 || key.which === 13) {
                return false;
            }
        });
        $("#id_description").on("keypress", function(key) {
            if ((key.which == 10 || key.which === 13) && key.ctrlKey) {
                $("#create-form").submit();
            }
        });
    });
</script>
{% endblock %}

rideup/templates/rideup/index.html
{% extends "rideup/base.html" %}

{% block head %}
<title>RideUp - Welcome</title>
{% endblock %}

{% block content %}
<div class="container">
    <h2>Welcome!</h2>
    {% if user.is_authenticated %}
        <h3 style="margin-bottom:20px;">Hello, {{ user.username }}! You are logged in and ready to create a ride!</h3>
        <form action="{% url 'logout' %}">
            <button type="submit" class="btn">Logout</button>
        </form>
    {% else %}
        <div class="row">
            <div class="col-md-4">
                <h3>Please log in:</h3>
                <form action="{% url 'login' %}" method="post" id="login-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>User name:</label>
                        <input class="form-control" type="text" id="id_username" name="username"
                               placeholder="username" required>
                    </div>
                    <div class="form-group">
                        <label>Password:</label>
                        <input class="form-control" type="password" id="id_password" name="password"
                               placeholder="password" required>
                    </div>
                    <button type="submit" class="btn">Login</button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <h3>or, create an account:</h3>
                <form action="{% url 'register' %}" autocomplete="off" method="post" id="create-user-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>User name:</label>
                        <input class="form-control" type="text" id="id_create_username" name="username"
                               placeholder="username" autocomplete="off" required>
                    </div>
                    <div class="form-group">
                        <label>Password:</label>
                        <input class="form-control" type="password" id="id_create_password1" name="password1"
                               placeholder="password" autocomplete="off" required>
                    </div>
                    <div class="form-group">
                        <label>Re-enter password:</label>
                        <input class="form-control" type="password" id="id_create_password2" name="password2"
                               placeholder="password" autocomplete="off" required>
                    </div>
                    <button type="submit" class="btn">Create Account</button>
                </form>
            </div>
        </div>
    {% endif %}
</div>

{% endblock %}

{% block foot %}
<script>
    $(document).ready(function() {
        $("#home-link").parent().addClass('active');
    });
</script>
{% endblock %}

rideup/templates/rideup/register_success.html
{% extends "rideup/base.html" %}

{% block head %}
<title>RideUp - Success!</title>
{% endblock %}

{% block content %}
<div class="container">
    <h2>Success! Welcome to RideUp</h2>
    Now go <a href="{% url 'create' %}">create a ride!</a>
</div>

{% endblock %}

rideup/templates/rideup/showrides.html
{% extends "rideup/base.html" %}
{% load staticfiles %}

{% block head %}
<title>Show Rides</title>
{% endblock %}

{% block content %}
<div class="container">
    <h2>Current Rides:</h2>
    <div class="row">
        <div class="col-md-4" style="height:600px; overflow:auto;">
            <ul id="rides_list" class="list-group">
            </ul>
        </div>
        <div class="col-md-8">
            <div id="map" style="margin-top:0px;">
                <div id="map_canvas"></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block foot %}
<script>
    $(document).ready(function() {
        $("#showrides-link").parent().addClass('active');
    });
    var mapRidesUrl = "{% url 'get_map_rides' %}";
</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAHu3tscS1tG243nstn6jiAS9L2kD1OwtQ&libraries=places&sensor=false"></script>
<script type="text/javascript" src="{% static 'rideup/js/rideup-show.js' %}"></script>
{% endblock %}